"""completion alternative table

Revision ID: 464492e039db
Revises: 70bb8d69c3a4
Create Date: 2025-04-17 14:38:53.532322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '464492e039db'
down_revision: Union[str, None] = '70bb8d69c3a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completion_alternatives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_completion_request_id', sa.UUID(), nullable=True),
    sa.Column('intercept_key', sa.String(length=200), nullable=True),
    sa.Column('alternative_content', sa.Text(), nullable=False),
    sa.Column('rater_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['intercept_key'], ['intercept_keys.intercept_key'], ),
    sa.ForeignKeyConstraint(['original_completion_request_id'], ['completions_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_completion_alternatives_intercept_key'), 'completion_alternatives', ['intercept_key'], unique=False)
    op.create_index(op.f('ix_completion_alternatives_rater_id'), 'completion_alternatives', ['rater_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_completion_alternatives_rater_id'), table_name='completion_alternatives')
    op.drop_index(op.f('ix_completion_alternatives_intercept_key'), table_name='completion_alternatives')
    op.drop_table('completion_alternatives')
    # ### end Alembic commands ###
