"""annotation targets and associations 1

Revision ID: 35ba05315e3d
Revises: 9e689ce66447
Create Date: 2025-04-19 07:01:27.418874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35ba05315e3d'
down_revision: Union[str, None] = '9e689ce66447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation_targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annotation_target_annotation_link',
    sa.Column('annotation_target_id', sa.UUID(), nullable=False),
    sa.Column('completion_annotation_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['annotation_target_id'], ['annotation_targets.id'], ),
    sa.ForeignKeyConstraint(['completion_annotation_id'], ['completion_annotations.id'], ),
    sa.PrimaryKeyConstraint('annotation_target_id', 'completion_annotation_id')
    )
    op.add_column('completion_alternatives', sa.Column('annotation_target_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'completion_alternatives', ['annotation_target_id'])
    op.create_foreign_key(None, 'completion_alternatives', 'annotation_targets', ['annotation_target_id'], ['id'])
    op.drop_constraint('completion_annotations_completion_id_fkey', 'completion_annotations', type_='foreignkey')
    op.drop_column('completion_annotations', 'completion_id')
    op.add_column('completion_responses', sa.Column('annotation_target_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'completion_responses', ['annotation_target_id'])
    op.create_foreign_key(None, 'completion_responses', 'annotation_targets', ['annotation_target_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'completion_responses', type_='foreignkey')
    op.drop_constraint(None, 'completion_responses', type_='unique')
    op.drop_column('completion_responses', 'annotation_target_id')
    op.add_column('completion_annotations', sa.Column('completion_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('completion_annotations_completion_id_fkey', 'completion_annotations', 'completion_responses', ['completion_id'], ['id'])
    op.drop_constraint(None, 'completion_alternatives', type_='foreignkey')
    op.drop_constraint(None, 'completion_alternatives', type_='unique')
    op.drop_column('completion_alternatives', 'annotation_target_id')
    op.drop_table('annotation_target_annotation_link')
    op.drop_table('annotation_targets')
    # ### end Alembic commands ###
