"""create_initial_schema

Revision ID: 81034ea6d3d9
Revises: 
Create Date: 2025-04-13 16:10:33.992216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81034ea6d3d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('log_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('intercept_key', sa.UUID(), nullable=True),
    sa.Column('request_method', sa.String(), nullable=True),
    sa.Column('request_url', sa.String(), nullable=True),
    sa.Column('request_headers', sa.JSON(), nullable=True),
    sa.Column('request_body', sa.JSON(), nullable=True),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.Column('response_headers', sa.JSON(), nullable=True),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_log_intercept_key'), 'requests_log', ['intercept_key'], unique=False)
    op.create_table('completion_responses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('request_log_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('created', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['request_log_id'], ['requests_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('completion_choices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('completion_id', sa.String(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('finish_reason', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['completion_id'], ['completion_responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('completion_choices')
    op.drop_table('completion_responses')
    op.drop_index(op.f('ix_requests_log_intercept_key'), table_name='requests_log')
    op.drop_table('requests_log')
    # ### end Alembic commands ###
