"""towards users

Revision ID: 4c111b1b034c
Revises: 35ba05315e3d
Create Date: 2025-04-20 15:32:21.715239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c111b1b034c'
down_revision: Union[str, None] = '35ba05315e3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('auth_provider', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_auth_provider'), 'users', ['auth_provider'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table('completion_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('creator_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_completion_projects_creator_id'), 'completion_projects', ['creator_id'], unique=False)
    op.create_table('completion_project_call_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['completion_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_completion_project_call_keys_key'), 'completion_project_call_keys', ['key'], unique=True)
    op.create_index(op.f('ix_completion_project_call_keys_project_id'), 'completion_project_call_keys', ['project_id'], unique=False)
    op.alter_column('agent_widgets', 'user_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using='user_id::uuid')
    op.create_foreign_key(None, 'agent_widgets', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('openrouter_guest_keys', 'user_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using='user_id::uuid')
    op.create_foreign_key(None, 'openrouter_guest_keys', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'openrouter_guest_keys', type_='foreignkey')
    op.alter_column('openrouter_guest_keys', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='user_id::varchar')
    op.drop_constraint(None, 'agent_widgets', type_='foreignkey')
    op.alter_column('agent_widgets', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='user_id::varchar')
    op.drop_index(op.f('ix_completion_project_call_keys_project_id'), table_name='completion_project_call_keys')
    op.drop_index(op.f('ix_completion_project_call_keys_key'), table_name='completion_project_call_keys')
    op.drop_table('completion_project_call_keys')
    op.drop_index(op.f('ix_completion_projects_creator_id'), table_name='completion_projects')
    op.drop_table('completion_projects')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_auth_provider'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
