"""structured for chat completions requests

Revision ID: dacffd233790
Revises: 81034ea6d3d9
Create Date: 2025-04-13 16:50:04.470972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dacffd233790'
down_revision: Union[str, None] = '81034ea6d3d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completions_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_log_id', sa.UUID(), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('messages_hash', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('response_format', sa.JSON(), nullable=True),
    sa.Column('response_format_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['request_log_id'], ['requests_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('completions_requests')
    # ### end Alembic commands ###
