"""completion alternative table 2

Revision ID: 38737c20aefa
Revises: 464492e039db
Create Date: 2025-04-17 14:48:54.726734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Import PG_UUID if you haven't already
from sqlalchemy.dialects.postgresql import UUID as PG_UUID


# revision identifiers, used by Alembic.
revision: str = '38737c20aefa'
down_revision: Union[str, None] = '464492e039db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Replace 'pass' with the create_table command
    op.create_table('completion_alternatives',
        sa.Column('id', PG_UUID(as_uuid=True), primary_key=True),
        sa.Column('original_completion_request_id', PG_UUID(as_uuid=True), sa.ForeignKey('completions_requests.id'), nullable=False), # Added nullable=False based on likely intent
        sa.Column('intercept_key', sa.String(length=200), sa.ForeignKey('intercept_keys.intercept_key'), nullable=False), # Added nullable=False based on likely intent
        sa.Column('alternative_content', sa.Text(), nullable=False),
        sa.Column('rater_id', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), # Added nullable=False
        # Add Foreign Key Constraints explicitly if needed, though ForeignKey() implies them
        # sa.ForeignKeyConstraint(['original_completion_request_id'], ['completions_requests.id'], ),
        # sa.ForeignKeyConstraint(['intercept_key'], ['intercept_keys.intercept_key'], ),
        # sa.PrimaryKeyConstraint('id') # Already defined by primary_key=True
    )
    # Add indexes separately if needed
    op.create_index(op.f('ix_completion_alternatives_intercept_key'), 'completion_alternatives', ['intercept_key'], unique=False)
    op.create_index(op.f('ix_completion_alternatives_rater_id'), 'completion_alternatives', ['rater_id'], unique=False)
    op.create_index(op.f('ix_completion_alternatives_original_completion_request_id'), 'completion_alternatives', ['original_completion_request_id'], unique=False) # Added index for FK

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Replace 'pass' with the drop_table command
    op.drop_index(op.f('ix_completion_alternatives_original_completion_request_id'), table_name='completion_alternatives') # Added index drop
    op.drop_index(op.f('ix_completion_alternatives_rater_id'), table_name='completion_alternatives')
    op.drop_index(op.f('ix_completion_alternatives_intercept_key'), table_name='completion_alternatives')
    op.drop_table('completion_alternatives')
    # ### end Alembic commands ###
