"""Add unique constraint to completion_request_id in CompletionResponse

Revision ID: 7db6899cfd09
Revises: da1e1d3590fb
Create Date: 2025-04-16 08:27:58.889808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7db6899cfd09'
down_revision: Union[str, None] = 'da1e1d3590fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'completion_responses', ['completion_request_id'])
    op.create_unique_constraint(None, 'intercept_keys', ['intercept_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'intercept_keys', type_='unique')
    op.drop_constraint(None, 'completion_responses', type_='unique')
    # ### end Alembic commands ###
