"""openrouter guest keys

Revision ID: 9a136893ef4a
Revises: 4b16558fd887
Create Date: 2025-04-15 15:57:09.807869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a136893ef4a'
down_revision: Union[str, None] = '4b16558fd887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('openrouter_guest_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('or_key_hash', sa.String(), nullable=False),
    sa.Column('or_name', sa.String(), nullable=False),
    sa.Column('or_label', sa.String(), nullable=False),
    sa.Column('or_disabled', sa.Boolean(), nullable=True),
    sa.Column('or_limit', sa.Integer(), nullable=True),
    sa.Column('or_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('or_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('or_key', sa.String(), nullable=False),
    sa.Column('or_usage', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_openrouter_guest_keys_or_key_hash'), 'openrouter_guest_keys', ['or_key_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_openrouter_guest_keys_or_key_hash'), table_name='openrouter_guest_keys')
    op.drop_table('openrouter_guest_keys')
    # ### end Alembic commands ###
