"""Change CompletionAnnotation rater_id to nullable user_id foreign key

Revision ID: 8c4b763e8744
Revises: fd1fb7a417c6
Create Date: 2025-04-22 15:28:41.668804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c4b763e8744'
down_revision: Union[str, None] = 'fd1fb7a417c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completion_annotations', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_completion_annotations_user_id'), 'completion_annotations', ['user_id'], unique=False)
    op.create_foreign_key(None, 'completion_annotations', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('completion_annotations', 'rater_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completion_annotations', sa.Column('rater_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'completion_annotations', type_='foreignkey')
    op.drop_index(op.f('ix_completion_annotations_user_id'), table_name='completion_annotations')
    op.drop_column('completion_annotations', 'user_id')
    # ### end Alembic commands ###
