"""completion alternative table 2 - ADJUSTED: Removed redundant create_table

Revision ID: 38737c20aefa
Revises: 464492e039db
Create Date: 2025-04-17 14:48:54.726734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Import PG_UUID if you haven't already
from sqlalchemy.dialects.postgresql import UUID as PG_UUID


# revision identifiers, used by Alembic.
revision: str = '38737c20aefa'
down_revision: Union[str, None] = '464492e039db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # NOTE: Removed op.create_table('completion_alternatives', ...) because
    #       it was already created in the previous migration (464492e039db).
    #       This migration might have been intended for modifications or was an error.
    #       If modifications were intended, add them here (e.g., op.alter_column).

    # Keep index creation if they weren't in the previous migration or are different
    # Check 464492e039db to see which indexes were already created.
    # op.create_index(op.f('ix_completion_alternatives_intercept_key'), 'completion_alternatives', ['intercept_key'], unique=False) # Already created in 464492e039db
    # op.create_index(op.f('ix_completion_alternatives_rater_id'), 'completion_alternatives', ['rater_id'], unique=False) # Already created in 464492e039db
    op.create_index(op.f('ix_completion_alternatives_original_completion_request_id'), 'completion_alternatives', ['original_completion_request_id'], unique=False) # This index seems new

    # Also adjust column nullability if needed, e.g.:
    op.alter_column('completion_alternatives', 'original_completion_request_id', nullable=False)
    op.alter_column('completion_alternatives', 'intercept_key', nullable=False)
    op.alter_column('completion_alternatives', 'created_at', nullable=False)


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Adjust downgrade based on what *this* migration actually does.
    # Since it primarily adds an index and alters nullability now:
    op.drop_index(op.f('ix_completion_alternatives_original_completion_request_id'), table_name='completion_alternatives')

    # Revert nullability changes (assuming they were nullable before)
    op.alter_column('completion_alternatives', 'original_completion_request_id', nullable=True)
    op.alter_column('completion_alternatives', 'intercept_key', nullable=True)
    op.alter_column('completion_alternatives', 'created_at', nullable=True)


    # NOTE: Do NOT drop the table here, as it was created by the previous migration.
    # op.drop_table('completion_alternatives')

    # ### end Alembic commands ###
