"""added raternotification

Revision ID: 1c8d78acf5c9
Revises: dacffd233790
Create Date: 2025-04-13 18:20:45.358894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c8d78acf5c9'
down_revision: Union[str, None] = 'dacffd233790'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completions_rater_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('rater_id', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('completion_response_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['completion_response_id'], ['completion_responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('completions_rater_notifications')
    # ### end Alembic commands ###
