"""add viewing_id to interceptkey

Revision ID: 70bb8d69c3a4
Revises: 7db6899cfd09
Create Date: 2025-04-16 09:06:07.051578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70bb8d69c3a4'
down_revision: Union[str, None] = '7db6899cfd09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intercept_keys', sa.Column('viewing_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_intercept_keys_viewing_id'), 'intercept_keys', ['viewing_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intercept_keys_viewing_id'), table_name='intercept_keys')
    op.drop_column('intercept_keys', 'viewing_id')
    # ### end Alembic commands ###
