"""completions annotations table

Revision ID: 465d24d1f3ef
Revises: 2a9088695025
Create Date: 2025-04-14 11:16:02.800430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '465d24d1f3ef'
down_revision: Union[str, None] = '2a9088695025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completion_annotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completion_id', sa.String(), nullable=True),
    sa.Column('rater_id', sa.String(), nullable=True),
    sa.Column('reward', sa.Float(), nullable=True),
    sa.Column('annotation_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['completion_id'], ['completion_responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('completion_annotations')
    # ### end Alembic commands ###
