"""agent widget table

Revision ID: 9e689ce66447
Revises: 1fcc8cbd684c
Create Date: 2025-04-18 08:55:24.180078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e689ce66447'
down_revision: Union[str, None] = '1fcc8cbd684c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_widgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cors_origin', sa.String(), nullable=False),
    sa.Column('tools', sa.JSON(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('n_calls', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('completion_alternatives', 'original_completion_request_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('completion_alternatives', 'intercept_key',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('completion_alternatives', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_completion_alternatives_original_completion_request_id', table_name='completion_alternatives')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_completion_alternatives_original_completion_request_id', 'completion_alternatives', ['original_completion_request_id'], unique=False)
    op.alter_column('completion_alternatives', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('completion_alternatives', 'intercept_key',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('completion_alternatives', 'original_completion_request_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_table('agent_widgets')
    # ### end Alembic commands ###
