"""added raternotification

Revision ID: 2a9088695025
Revises: 1c8d78acf5c9
Create Date: 2025-04-13 18:44:39.743648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a9088695025'
down_revision: Union[str, None] = '1c8d78acf5c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completions_rater_notifications', sa.Column('intercept_key', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('completions_rater_notifications', 'intercept_key')
    # ### end Alembic commands ###
