"""added intercept key table

Revision ID: 4b16558fd887
Revises: 465d24d1f3ef
Create Date: 2025-04-15 12:51:35.959590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b16558fd887'
down_revision: Union[str, None] = '465d24d1f3ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intercept_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('intercept_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intercept_key')
    )
    op.create_index(op.f('ix_intercept_keys_user_id'), 'intercept_keys', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intercept_keys_user_id'), table_name='intercept_keys')
    op.drop_table('intercept_keys')
    # ### end Alembic commands ###
