"""make intercept_keys.user_is_guest nullable

Revision ID: 38d9675390d5
Revises: 9a136893ef4a
Create Date: 2025-04-15 16:44:52.124623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d9675390d5'
down_revision: Union[str, None] = '9a136893ef4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intercept_keys', sa.Column('user_is_guest', sa.Boolean(), nullable=True))
    op.add_column('openrouter_guest_keys', sa.Column('user_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('openrouter_guest_keys', 'user_id')
    op.drop_column('intercept_keys', 'user_is_guest')
    # ### end Alembic commands ###
